### ISSUE TITLE
Thread main panics whenever you attempt to run a place

### ISSUE THREAD

**Issue by Jaguar-515** [rojo-rbx/run-in-roblox#12]
Whenever you attempt to run a place, it always makes the thread main panic.

![image](https://user-images.githubusercontent.com/48777426/68550346-dd4d8e00-03b6-11ea-8927-5cee03ba4c94.png)

**Comment by Jaguar-515** [comment]
Revisiting this bug, it appears that it panics when Lua code isn't provided even though the place file contains it.

Below is a .zip file that'll let you attempt to reproduce this. Make sure to read the README in the file for instructions to reproduce this.

[repro.zip](https://github.com/rojo-rbx/run-in-roblox/files/4395493/repro.zip)

**Comment by LPGhatguy** [comment]
I believe this behavior itself is not a bug in run-in-roblox, but having a panic here is definitely a bug.

It's a known limitation that the code in your game, since run-in-roblox has no way to actually start playing the place as far as I can tell. Because of that, the actual code that runs has to be passed into the game and is run as a plugin, not like a normal game.

We might be able to figure out some undocumented flags to pass to Roblox Studio to get it to play, but until then, it's a requirement to pass code to run explicitly.

**Comment by LPGhatguy** [comment]
This case should no longer panic.
